requires 'App::Cmd';
requires 'Config::Tiny';
requires 'DateTime';
requires 'DateTime::Format::ISO8601';
requires 'File::Basename';
requires 'File::Slurp';
requires 'lib';
requires 'LWP::Protocol::https';
requires 'LWP::UserAgent';
requires 'Moo';
requires 'Moose';
requires 'Mozilla::CA', '>=20211001';
requires 'Text::CSV';
requires 'URI';
requires 'XML::Rabbit';
